### PR TITLE
Addition of twitter oauth login functions and its test code

### PR DESCRIPTION
**Pull request by starcharles**
Added twitter-oauth verification and its test-code

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks for your contribution. I will give it a try later.
In the meantime, could you work on these?

1. change the title so that it means what this pull request is.
2. squash commits to be just one commit.
3. set your name something other than "Your Name".
4. don't edit the .gitignore file

**Comment by starcharles** [comment]
Thanks for your sagguestion .I trying to fix them.But on squash ,it seems to be difficult with some eroor
I'll try it

**Comment by dai-shi** [comment]
The title seems too long: how about this? "Addition of twitter oauth login functions and its test code"

If you are having trouble with squashing commits, another way would be creating a new branch.

**Comment by starcharles** [comment]
I will try to do new PR with other new branch

**Pull request closed without merging**
